version: "3.4"

services:
  cryptocurrency-api:
    image: "cryptocurrency-api:latest"
    environment:
      - MONGO_URI=mongodb://mongo:27017/db
    build: .
    ports:
      - "5005:5005"
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: "mongo"
    volumes:
      - ./database:/data
    ports:
      - "27017:27017"
