on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
    
name: Build & Covergae
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x,]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node JS
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Generate Coverage
      run: |
        npm install
        npm run test:cov
    
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: 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
        SONAR_TOKEN: 98ac242cc269f901d34077c11d4c6f79375c0a4e
